# Generated by Django 3.0.2 on 2020-02-11 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_auto_20200211_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-created', '-id')},
        ),
        migrations.AddField(
            model_name='guide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guidecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
