# Generated by Django 3.0.2 on 2020-02-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20200211_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-created', '-id'), 'verbose_name': '服务指南'},
        ),
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'verbose_name': '服务指南分类'},
        ),
        migrations.AlterField(
            model_name='guide',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.GuideCategory', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='file',
            field=models.FileField(upload_to='guides', verbose_name='指南文件'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=255, verbose_name='服务指南名称'),
        ),
        migrations.AlterField(
            model_name='guidecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='类别名称'),
        ),
    ]
