# Generated by Django 3.0.2 on 2020-02-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20200213_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-created', '-id'), 'verbose_name': '指南清单', 'verbose_name_plural': '指南清单'},
        ),
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'verbose_name': '服务指南分类', 'verbose_name_plural': '服务指南分类'},
        ),
    ]
