# Generated by Django 3.0.2 on 2020-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20200215_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ('-created', '-id'), 'verbose_name': '指南文件', 'verbose_name_plural': '指南文件'},
        ),
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'verbose_name': '指南分类', 'verbose_name_plural': '指南分类'},
        ),
    ]
