# Generated by Django 3.0.2 on 2020-02-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_auto_20200217_2235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'ordering': ('name', '-id'), 'verbose_name': '指南分类', 'verbose_name_plural': '指南分类'},
        ),
    ]
