# Generated by Django 3.0.2 on 2020-01-22 12:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('form_metas', django_mysql.models.JSONField(default=dict)),
            ],
        ),
    ]
