# Generated by Django 3.0.2 on 2020-01-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20200122_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='time',
            new_name='time_end',
        ),
        migrations.AddField(
            model_name='activity',
            name='open_for_enrollment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activity',
            name='participants_total_limit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='time_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_time', models.DateTimeField(auto_now_add=True)),
                ('participating_metas', django_mysql.models.JSONField(default=dict)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
