# Generated by Django 3.0.2 on 2020-01-24 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200122_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'permissions': [('enroll_activities_not_open_for_enrollment', 'Can enroll activities that are not open for enrollment')]},
        ),
    ]
