# Generated by Django 3.0.2 on 2020-01-24 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
    ]
