# Generated by Django 3.0.2 on 2020-01-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_auto_20200124_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='activity.Activity'),
        ),
    ]
