# Generated by Django 3.0.2 on 2020-01-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0007_auto_20200127_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='active',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activity.Activity'),
        ),
    ]
