# Generated by Django 3.0.2 on 2020-01-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20200128_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='form_metas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participating_metas',
            field=models.TextField(),
        ),
    ]
