# Generated by Django 3.0.2 on 2020-02-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_auto_20200210_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinmeta',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='generated_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
