# Generated by Django 3.0.2 on 2020-02-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_auto_20200210_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinmeta',
            name='need_enrollment',
            field=models.BooleanField(default=True),
        ),
    ]
