# Generated by Django 3.0.2 on 2020-02-10 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0014_clockinmeta_need_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockinmeta',
            name='from_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clockinmeta',
            name='to_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
