# Generated by Django 3.0.2 on 2020-02-10 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0015_auto_20200210_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created', '-id')},
        ),
        migrations.AlterModelOptions(
            name='clockinmeta',
            options={'ordering': ('-created', '-id')},
        ),
        migrations.AlterModelOptions(
            name='clockinrecord',
            options={'ordering': ('-created', '-id')},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-enroll_time', '-id')},
        ),
        migrations.AddField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
