# Generated by Django 3.0.2 on 2020-02-15 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0016_auto_20200210_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created', '-id'), 'verbose_name': '活动清单', 'verbose_name_plural': '活动清单'},
        ),
        migrations.AlterModelOptions(
            name='clockinmeta',
            options={'ordering': ('-created', '-id'), 'verbose_name': '打卡配置', 'verbose_name_plural': '打卡配置'},
        ),
        migrations.AlterModelOptions(
            name='clockinrecord',
            options={'ordering': ('-created', '-id'), 'verbose_name': '打卡记录', 'verbose_name_plural': '打卡记录'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ('-enroll_time', '-id'), 'verbose_name': '报名记录', 'verbose_name_plural': '报名记录'},
        ),
        migrations.RemoveField(
            model_name='clockinmeta',
            name='need_enrollment',
        ),
        migrations.AlterField(
            model_name='activity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='form_metas',
            field=models.TextField(verbose_name='报名表单'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='location',
            field=models.CharField(max_length=200, verbose_name='活动地点'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=30, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='open_for_enrollment',
            field=models.BooleanField(default=False, verbose_name='开放报名？'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='participants_total_limit',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='参与者总数限制'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_end',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='time_start',
            field=models.DateTimeField(verbose_name='起始时间'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='changed',
            field=models.DateTimeField(auto_now=True, verbose_name='修改日期'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='from_time',
            field=models.DateTimeField(verbose_name='有效时间（从）'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='generated_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='打卡码'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='label',
            field=models.CharField(max_length=32, verbose_name='打卡标签'),
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='to_time',
            field=models.DateTimeField(verbose_name='有效时间（到）'),
        ),
        migrations.AlterField(
            model_name='clockinrecord',
            name='clockin_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ClockinMeta', verbose_name='打卡配置'),
        ),
        migrations.AlterField(
            model_name='clockinrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='打卡时间'),
        ),
        migrations.AlterField(
            model_name='clockinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='打卡用户'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='报名时间'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='participating_metas',
            field=models.TextField(verbose_name='参与信息'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
