# Generated by Django 3.0.2 on 2020-02-17 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0017_auto_20200215_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-created', '-id'), 'verbose_name': '活动', 'verbose_name_plural': '活动'},
        ),
        migrations.AlterModelOptions(
            name='clockinmeta',
            options={'ordering': ('-created', '-id'), 'verbose_name': '打卡项', 'verbose_name_plural': '打卡项'},
        ),
        migrations.AlterModelOptions(
            name='clockinrecord',
            options={'ordering': ('-created', '-id'), 'verbose_name': '打卡历史', 'verbose_name_plural': '打卡历史'},
        ),
        migrations.AlterField(
            model_name='clockinmeta',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockins', to='activity.Activity', verbose_name='活动'),
        ),
        migrations.AlterField(
            model_name='clockinrecord',
            name='clockin_meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.ClockinMeta', verbose_name='打卡项'),
        ),
        migrations.AlterField(
            model_name='clockinrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockin_records', to=settings.AUTH_USER_MODEL, verbose_name='打卡用户'),
        ),
    ]
