# Generated by Django 3.0.2 on 2020-02-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0018_auto_20200217_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='名称'),
        ),
    ]
