# Generated by Django 3.0.2 on 2020-02-18 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0019_auto_20200218_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockinStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockin_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockin_staffs', to='activity.ClockinMeta', verbose_name='打卡项')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='打卡员')),
            ],
            options={
                'verbose_name': '打卡员',
                'verbose_name_plural': '打卡员',
                'unique_together': {('clockin_meta', 'staff')},
            },
        ),
    ]
