# Generated by Django 3.0.2 on 2020-01-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200125_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechat_open_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
