# Generated by Django 3.0.2 on 2020-02-12 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_contact_usermeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='post',
            field=models.CharField(default='aaa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL),
        ),
    ]
