# Generated by Django 3.0.2 on 2020-02-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200212_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='nickname',
        ),
    ]
