# Generated by Django 3.0.2 on 2020-02-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200212_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='wechat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
