# Generated by Django 3.0.2 on 2020-02-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200212_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='qq',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='tel',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
