# Generated by Django 3.0.2 on 2020-02-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20200213_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='qq',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
