# Generated by Django 3.0.2 on 2020-02-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200213_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '通讯录人员关系', 'verbose_name_plural': '通讯录人员关系'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '教师用户', 'verbose_name_plural': '教师用户'},
        ),
        migrations.AlterModelOptions(
            name='usermeta',
            options={'verbose_name': '教师通讯录信息', 'verbose_name_plural': '教师通讯录信息'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='friend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='同事'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_open_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='微信openid'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='post',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='qq',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='QQ'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='tel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='usermeta',
            name='wechat',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='微信'),
        ),
    ]
