# Generated by Django 3.0.2 on 2020-02-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200215_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': '教师用户', 'verbose_name_plural': '教师用户'},
        ),
    ]
