# Generated by Django 3.0.2 on 2020-02-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200219_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='系所')),
            ],
            options={
                'verbose_name': '系所',
                'verbose_name_plural': '系所',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='usermeta',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_users', to='user.Department', verbose_name='系所'),
        ),
    ]
