# Generated by Django 3.0.2 on 2020-02-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200226_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_users', to='user.Department', verbose_name='系所'),
            preserve_default=False,
        ),
    ]
