# Generated by Django 3.0.2 on 2020-02-27 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200226_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '好友关系', 'verbose_name_plural': '好友关系'},
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_users', to='user.Department', verbose_name='系所'),
        ),
    ]
