# Generated by Django 3.0.2 on 2020-02-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20200227_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='friend_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='好友'),
        ),
    ]
