# Generated by Django 3.0.2 on 2020-02-15 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservation', '0005_auto_20200210_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'verbose_name': '会议室', 'verbose_name_plural': '会议室'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-created', '-id'), 'verbose_name': '预约记录', 'verbose_name_plural': '预约记录'},
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='description',
            field=models.TextField(verbose_name='会议室简介'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='label',
            field=models.CharField(max_length=32, verbose_name='会议室标签'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='location',
            field=models.CharField(max_length=128, verbose_name='会议室位置'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='name',
            field=models.CharField(max_length=32, verbose_name='会议室名称'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='seats_count',
            field=models.IntegerField(verbose_name='会议室座位数'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='预约时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(verbose_name='预约原因'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='meetingroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservation.Meetingroom', verbose_name='会议室'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_from',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_to',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='预约者'),
        ),
    ]
