# Generated by Django 3.0.2 on 2020-02-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_auto_20200215_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='description',
            field=models.TextField(blank=True, verbose_name='会议室简介'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='label',
            field=models.CharField(blank=True, max_length=32, verbose_name='会议室标签'),
        ),
    ]
