# Generated by Django 3.0.2 on 2020-02-21 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_auto_20200218_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='label',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='location',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserve_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='预约日期'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_from',
            field=models.IntegerField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_to',
            field=models.IntegerField(verbose_name='结束时间'),
        ),
    ]
