# Generated by Django 3.0.2 on 2020-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200221_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='会议室名称'),
        ),
    ]
