# Generated by Django 3.0.2 on 2020-02-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_auto_20200221_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_from',
            field=models.TimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_to',
            field=models.TimeField(verbose_name='结束时间'),
        ),
    ]
