# Generated by Django 3.0.2 on 2020-02-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_auto_20200221_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reserve_date',
        ),
    ]
