# Generated by Django 3.0.2 on 2020-02-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_remove_reservation_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_from',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserve_to',
            field=models.DateTimeField(verbose_name='结束时间'),
        ),
    ]
